### ISSUE TITLE
Identify Water Filter ERD

### ISSUE THREAD

**Issue by bendavis** [simbaja/gehome#12]
I'm working on identifying the ERD codes for the "smart" GE water filter GXWH70M.

I know (or at least a high level of confidence):
0x115f = filter state, 00 = bypass, 01 is off, 02 = filter, other value is unknown
0x1160 = flow rate, I think displayed with %.2f
0x1164 = filter life, read by converting the first 8 chars from hex to dec, then appending a percent. I don't know what the last 16 chars are.
0x1668 = manual mode flag (1 on, 0 off)
0x1169 = continuous flow alert, low, medium, high are read as a bit field (val &1, val&2, val&4)
0x116a = flow alert settings - low is value[0:3], medium[4:7], high[8:11] convert from hex
0x116d = todays water usage
0x116e = leak validity - as far as I can tell posted back when the user confirms a leak (yes = 1, no = 0)

I also know that 0x115e is the valve water state, maybe what is written to to change the filter configuration between off, bypass, and filtered.

0x1167 sometimes changes on filter transitions, but I have no idea what this is yet.

0x1163 is a mystery to me.

I haven't been able to find a way to figure out how usage plots are retrieved. That information doesn't appear to come from ERD. Is there anything analogous to this in other GE products?

**Comment by bendavis** [comment]
Okay notification history is at- /v1/appliance/{mac}/message - also works on GE ovens. Things like:

```
client > Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{"kind": "websocket#api", "action": "api", "host": "api.brillion.geappliances.com", "method": "GET", "path": "/v1/appliance/xxxxxxxxxxxxx/message", "id": "xxxxxxxxxxxxx"}', rsv1=False, rsv2=False, rsv3=False)
client - event = data_received(<308 bytes>)
client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{"kind":"websocket#api","id":"xxxxxxxxxxxxx","request":{"host":"api.brillion.geappliances.com","method":"GET","path":"/v1/appliance/xxxxxxxxxxxxx/message"},"success":true,"code":200,"body":{"kind":"appliance#messageList","userId":"xxxxxxxxxxxxx","applianceId":"xxxxxxxxxxxxx","items":[{"time":"time","message":"Your Oven\'s Preheat is Complete"},...]}}', rsv1=False, rsv2=False, rsv3=False)
```

**Comment by warrenrees** [comment]
Hi Ben,

I've started adding some of these into my development branch, would you be able to attach a log of what's currently being output?

**Comment by bendavis** [comment]
I've actually put most of it on my fork. I've also got some of the home assistant integration working that I need to push up. I'll put in a pull request soon
