### ISSUE TITLE
Is there a little more detail on what this project can/can't do/plans?

### ISSUE THREAD

**Issue by chansearrington** [simbaja/gehome#15]
Hey there,

Just bought a GE washer, dryer, dishwasher and refrigerator and excited to get these into HA. OR at least help to.

Is there more information somewhere that shows where this project is? What it can do. What it can't. What you need help with? Is there a working integration with Home Assistant? How to intall? etc.

Here's an example:

https://github.com/tsightler/ring-mqtt

**Comment by simbaja** [comment]
We're reverse engineering the GE protocols to add as many smart appliances as we can figure out.  We are in process of adding full washer/dryer, advantium, and water filter support.  You can help by running the websocket example and posting the debug log so we can check to make sure that we have at least identified all the ERD codes (even if we haven't figured out what they represent).  From there, if you can assist in trying to help identify what an ERD code does and its possible values, that is helpful.

In terms of HA support, please see the simbaja\ha_components repository, it is a custom integration that utilizes this library and can be installed like any other custom component in HA (either manually or through HACS).

**Comment by chansearrington** [comment]
Awesome, will do so this weekend and post it back. Where do you want me to post the debug log?

**Comment by simbaja** [comment]
If you want to post here, I think that'll work.  @warrenrees is mainly concentrating on the laundry support and I'm trying to take on the other devices.  Also, the "dev" branch of the ha_components repository has the latest version of the HA component inclusive of all the support that's integrated so far.  Since you have multiple devices, it would be great if you could grab that and confirm it's all working as expected before we drop it into the main branch.

**Comment by RobertusIT** [comment]
Please can someone explain how to use this sdk, to help devs ? 

I have some General Electric AC, so i wish to integrate it in Home Assistant, also because Ge Appliances app is terrible.

**Comment by simbaja** [comment]
I've updated the readme file to add additional help for usage that hopefully helps.  Basically, if there's a device that you'd like supported (or if we're missing functionality you want for an existing device), you'll need to create a new issue and post a debug log from the websocket_example output.  We implement the base functionality in the SDK, then use that to add corresponding functionality in the HA component (see simbaja\ha_components).  The current dev component has support for ovens, dishwashers, advantium, laundry, and water filters.

**Comment by RobertusIT** [comment]
Thanks to reply.

I make **pip install gehomesdk** and install sdk

Then nano secrets.py and I use my credentials in SmartHQ app, that in europe is [Ge Appliances](https://play.google.com/store/apps/details?id=com.ge.comfort&hl=it&gl=US)

And now? How can i launch **websocket_example.py** where is ?

I can't install **locate** in home assistant, so i don't know where is this file.

Also, after launch **websocket_example.py**, needed more something or only my AC on ? So get automatically debug log?

If yes, where can i get it, to open an issue here on github?

Thanks for the support
