### ISSUE TITLE
Installed GE integration but never prompted for Credentials so not working

### ISSUE THREAD

**Issue by cartercsmith** [simbaja/gehome#28]
Simbaja:
Let me start by saying thanks so much for contributing to HA. Great stuff. 

I have GE washers and I wanted to try out the integration. I installed your repo using HACS, restarted HA, but seem stuck there. Did not see any way to configure the integration. When I click down in the lower corner of the integration, I get a drop down and one says Update Information but no response when clicked.

I tried installing the latest beta and same situation.

Can I manually add the credentials for GE smart Home in a config file somewhere and get over the hump? I'm also more than happy to provide log files or any other testing you need to help with the project.  Appreciate any thoughts and thanks again.

**Comment by simbaja** [comment]
Can you post a screenshot of what you're seeing?  Did you go to your HA integrations page and add the integration there (like the built-in integrations) after adding the integration library itself using HACS?
