### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [simbaja/gehome#32]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

Thanks

**Comment by mjohannessen** [comment]
I'm getting this error: 

.../gehome-master/examples/websocket_example.py:74: DeprecationWarning: The object should be created within an async function
  session = aiohttp.ClientSession()

which may have lead to another error:

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
