### ISSUE TITLE
Coffee Maker - Functionality Limited

### ISSUE THREAD

**Issue by kksligh** [simbaja/gehome#35]
I have model C7CDAASP1 coffee maker.  I'm on the latest v0.5.0 and I've tried all other dev versions available on HACS.  

The only functionality that is showing up is Sabbath Mode on/off switch.  I was hoping some of the app functionality would come through:

- Brew Controls - Brew Strength, Brew Temp, Brew Size
- Auto Brew - Set Schedule
- Descaling - On/Off switch

I'll attach logs shortly.

**Comment by kksligh** [comment]
[GE Home Debug Log - 1.31.22.txt](https://github.com/simbaja/gehome/files/7972897/GE.Home.Debug.Log.-.1.31.22.txt)

**Comment by kksligh** [comment]
Not sure if these logs are what you need.  Let me know if there is anything else I can do to help.

**Comment by ssryan9** [comment]
I'm having this issue as well. Not seeing any devices or entities related to the coffee maker

**Comment by simbaja** [comment]
The coffee maker support isn't complete in HA.  

However, if you pull down this repository and follow the directions in the readme (i.e. run the websocket_example.py found in the examples directory after creating the credentials file), you should be able to generate the logs that I'd need to confirm that the library can see the coffee maker appropriately and we can complete the HA implementation.

Hope this helps.

**Comment by kksligh** [comment]
@simbaja can you help with my request?

**Comment by simbaja** [comment]
> @simbaja can you help with my request?

To which request are you referring?   The original request for coffee maker support?  If so, the logs provided don't really help because the version of the library that is being used in Home Assistant is older and doesn't support any of the coffee maker functionality.

**Comment by kksligh** [comment]
I can't figure out how to update the code. That's my main issue right now. The files in the custom component folder in HA are completely different than these. I tried deleting and then uploading these manually but it didn't work.. As noted I couldn't find the repository on HACS

**Comment by simbaja** [comment]
You can't upload this project directly into Home Assistant, this is a communication library for GE appliances, not a HA integration.  The integration should still be compatible with HACS, but there have been breaking changes in HA itself, by keeping HA fully up to date, it may make some integrations incompatible.  It's possible that may be happening, but you'd have to check your logs.  You also should be adding the ha_gehome repository, not the gehome repository into HACS.

**Comment by kksligh** [comment]
Got it - sorry for all the basic questions. I know just enough to break things at this point.

Thanks,

Kale Sligh

VP, Marketing
o 615.744.1206
m 615.917.1441
________________________________

**Comment by kksligh** [comment]
I feel like such an idiot - I was working with the wrong code base.  I used HA_GEHOME everything went easily!  Everything is working smoothly and the Coffee Marker errors are fixed.  Tons of functionality!
