### ISSUE TITLE
Microwave - Not Showing Up in HA

### ISSUE THREAD

**Issue by kksligh** [simbaja/gehome#36]
I purchased the Cafe Microwave model: CEB515P3MDS.  The functionality currently in the GE App are as follows:

- Status
- Add 30 Seconds
- Scan to Cook

Currently, the microwave doesnt show up in HA at all. 

I'll add logs shortly.

**Comment by kksligh** [comment]
[GE Home Debug Log - 1.31.22.txt](https://github.com/simbaja/gehome/files/7972887/GE.Home.Debug.Log.-.1.31.22.txt)

**Comment by kksligh** [comment]
Not sure if these logs are what you need.  Let me know if there is anything else I can do to help.

**Comment by simbaja** [comment]
The microwave support isn't complete in HA.  

However, if you pull down this repository and follow the directions in the readme (i.e. run the websocket_example.py found in the examples directory after creating the credentials file), you should be able to generate the logs that I'd need to confirm that the library can see the microwave appropriately and we can complete the HA implementation.

Hope this helps.

**Comment by kksligh** [comment]
I got it to show with the code you outlined above.  While it is working, I am getting the following errors:

Logger: gehomesdk.erd.converters.microwave.erd_microwave_cook_setting_converter
Source: /usr/local/lib/python3.9/site-packages/gehomesdk/erd/converters/microwave/erd_microwave_cook_setting_converter.py:27
First occurred: 8:13:31 AM (26 occurrences)
Last logged: 8:26:01 AM

Could not construct cook setting, using default.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/erd/converters/microwave/erd_microwave_cook_setting_converter.py", line 20, in erd_decode
    return ErdMicrowaveCookSetting(
TypeError: <lambda>() got an unexpected keyword argument 'cook_mins'

**Comment by simbaja** [comment]
That typo should be fixed, can you check again and post your logs from the websocket example?

**Comment by kksligh** [comment]
Has this been pulled off HACS? I'm having some issues updating the code. I'm not super experienced with gitHub. My assumption is I need to delete the old files from the custom_components repository and upload these new ones but I'm unable to delete all the folders. How do I easily update the code? I looked on HACS and don't see it at all anymore.

**Comment by simbaja** [comment]
Basically, this library is what Home Assistant uses for its underlying communications.  It doesn't technically have to be used with Home Assistant, it can be used with anything that interfaces with Python.

I didn't pull the integration off of HACS; however, it may perhaps be a versioning issue where it doesn't like the newer versions.  Did you recently update HA?

**Comment by kksligh** [comment]
Yes, I have the latest builds for everything. 

core-2022.4.7
supervisor-2022.04.0
Home Assistant OS 7.6
