### ISSUE TITLE
Interested in getting this to work with OpenHAB

### ISSUE THREAD

**Issue by Mr-jreeves** [simbaja/gehome#4]
I'm a novice user of OpenHAB but in the process of porting my SmartThings / WebCore to OpenHAB. I currently am using the GE IFTTT to get notifications of Washer/Dryer events and would really like to get this working in OH without IFTTT.

Also, not sure if this is the right place to raise this issue... I know the repository was just moved here.... I'm also a novice githubber. :-)

**Comment by Mr-jreeves** [comment]
Got the sample running and retrieved the status from my Washer and Dryer! Just FYI, at first I was getting all sorts of python errors .. it turns out my Login Credentials were wrong ... I got a new password from the SmartHQ and everything just worked :-)

BTW, for the USERNAME and PASSWORD, I just created a secret.py in the top level and defined them with my Username and Password strings.

**Comment by Mr-jreeves** [comment]
I am trying to follow the code to figure out how to make a simple polling client to watch for changes (in order to help figure out what the ERDs are) ... but following async python is twisting my old brain ... 

Is there a simple example of using the blocking functions that I can start with?

**Comment by simbaja** [comment]
You may want to check out the HA component (simbaja\ha_components) for ideas about how to utilize in OpenHAB.  I don't have any experience with that system's requirements though.
