### ISSUE TITLE
Possibility of local-only (no cloud) mode?

### ISSUE THREAD

**Issue by BHSPitMonkey** [simbaja/gehome#40]
This is probably a tall order based on what I've seen of the API notes so far, but has anyone here explored the feasibility of talking to these devices directly (e.g. by emulating the role GE's backend application plays, or reverse engineering whatever built-in APIs exist on the appliances themselves?

If the SmartHQ cloud is functioning mostly as a broker for the commands/messages used by the appliances, it seems like the compatibility layer might be fairly thin and easily replaced (the authentication/enrollment flows could be tricky, though).

**Comment by simbaja** [comment]
@johnnypicnic appears to be working in that direction based on another issue.  It should be possible to do this, the RJ 45 port on these devices allows you to communicate using a serial protocol.  You may also want to look at "Green Bean" which was the original device for interacting with appliances, I think there is documentation and possibly schematics.
