### ISSUE TITLE
add to requirements.txt

### ISSUE THREAD

**Issue by tcgoetz** [simbaja/gehome#50]
After installing with:

`pip install gehomesdk`

I run and get the following errors:

```
ModuleNotFoundError: No module named 'lxml'
...
ModuleNotFoundError: No module named 'slixmpp'
```

requirements.txt needs the following lines added:

```
lxml
slixmpp
```

**Comment by tcgoetz** [comment]
I installed gehomesdk into a fresh venv (no packages installed) and got errors when I tried to run the utility. After installing those packages manually, the utility ran fine. I would guess you installed it into a system that already had those packages installed.

I don't see either of those packages as part of the collected packages in your listing.

**Comment by gleepwurp** [comment]
Hi, makes sense, I just checked and you are correct, they were already installed. my bad!

**Comment by simbaja** [comment]
Should be done in the source, will publish a new version with the changes as well to pypi, thanks!
