### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by greisch1** [simbaja/gehome#69]
Can no longer authenticate in Home Assistant.

**Comment by spbrogan** [comment]
for me i had the same problem.  to resolve I had to use their own website to fix my account.  login here: https://accounts.brillion.geappliances.com/consumer/login

it forced me to reset my password and then accept a few new terms.  two different times I had to approve new terms.  Once I was fully logged in through the website then the HA authenticate worked.

**Comment by rhpot1991** [comment]
I had to:

1. Update my password
2. Login to the GE app which then prompted me for a new ToS

Until I did both, HA failed to auth.

**Comment by simbaja** [comment]
I think the directions here and in the updated pinned issues in the integration repo should generally resolve this issue, please feel free to comment again if it's another issue.
